-- MySQL Script generated by MySQL Workbench
-- Sun Jul  7 19:41:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_colocho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_colocho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_colocho` DEFAULT CHARACTER SET utf8 ;
USE `db_colocho` ;

-- -----------------------------------------------------
-- Table `db_colocho`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `documento_usuario` BIGINT(20) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `documento_cliente` BIGINT(20) NOT NULL,
  `direcccion_cliente` VARCHAR(45) NOT NULL,
  `correo_cliente` VARCHAR(45) NOT NULL,
  `telefono_cliente` BIGINT(20) NOT NULL,
  `telefono2_cliente` BIGINT(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`proveedores` (
  `idproveedores` INT NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `documento_proveedor` BIGINT(20) NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  `correo_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(45) NOT NULL,
  `Telefono2_proveedor` BIGINT(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` BIGINT(20) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `stock_producto` BIGINT(20) NOT NULL,
  `stock_limite` BIGINT(20) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`compras` (
  `idcompras` INT NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(45) NOT NULL,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` BIGINT(11) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_colocho`.`ventas_mayor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_colocho`.`ventas_mayor` (
  `idventas_mayor` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(45) NOT NULL,
  `documento` BIGINT(20) NOT NULL,
  `telefono` BIGINT(20) NOT NULL,
  `telefono2` BIGINT(20) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` BIGINT(11) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idventas_mayor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
