/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Mufasa
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        System.setProperty("flatlaf.menuBarEmbedded", "false");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boton_CerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nombre_Usuario = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        idUsuario = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Validar_Ventas_Bar = new javax.swing.JLabel();
        Validar_Gestionar_Clientes = new javax.swing.JLabel();
        Validar_Ventas_Por_Mayor = new javax.swing.JLabel();
        Validar_Gestionar_Proveedores = new javax.swing.JLabel();
        Validar_Gestionar_Compras = new javax.swing.JLabel();
        Validar_Gestionar_Productos = new javax.swing.JLabel();
        Validar_Gestionar_Categorias = new javax.swing.JLabel();
        Validar_Inventario = new javax.swing.JLabel();
        Validar_Gestionar_Usuarios = new javax.swing.JLabel();
        Validar_Gestionar_Mesas = new javax.swing.JLabel();
        Validar_Gestionar_Negocio = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        Menu_Ventas = new javax.swing.JMenu();
        Menu_VentasBar = new javax.swing.JMenuItem();
        Menu_VentasPorMayor = new javax.swing.JMenuItem();
        Menu_Clientes = new javax.swing.JMenu();
        Menu_Gestionar_Clientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu_Proveedores = new javax.swing.JMenu();
        Menu_Gestionar_Proveedores = new javax.swing.JMenuItem();
        Menu_Compras = new javax.swing.JMenu();
        Menu_Gestionar_Compras = new javax.swing.JMenuItem();
        Menu_Productos = new javax.swing.JMenu();
        Menu_Gestionar_Productos = new javax.swing.JMenuItem();
        Menu_Reportes = new javax.swing.JMenu();
        Menu_Reporte_Inventario = new javax.swing.JMenuItem();
        Menu_Reporte_Ventas_Bar = new javax.swing.JMenuItem();
        Menu_Reporte_Ventar_Por_Mayor = new javax.swing.JMenuItem();
        Menu_Gestion = new javax.swing.JMenu();
        Menu_Registro_Usuarios = new javax.swing.JMenuItem();
        Menu_Mesas = new javax.swing.JMenuItem();
        Menu_Datos_Negocio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Panel Principal");
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(1366, 729));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1366, 729));
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 729));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 729));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Boton_CerrarSesion.setBackground(new java.awt.Color(229, 57, 53));
        Boton_CerrarSesion.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        Boton_CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        Boton_CerrarSesion.setText("Cerrar Sesion");
        Boton_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar.png"))); // NOI18N
        jLabel1.setText("Usuario:");

        Nombre_Usuario.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Nombre_Usuario.setText("Name User");

        Username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Username.setText("Username");

        idUsuario.setText("0");

        Rol.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Rol.setText("Rol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nombre_Usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69)
                                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_Usuario)
                    .addComponent(idUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(Rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Validar_Ventas_Bar.setText("0");

        Validar_Gestionar_Clientes.setText("0");

        Validar_Ventas_Por_Mayor.setText("0");

        Validar_Gestionar_Proveedores.setText("0");

        Validar_Gestionar_Compras.setText("0");

        Validar_Gestionar_Productos.setText("0");

        Validar_Gestionar_Categorias.setText("0");

        Validar_Inventario.setText("0");

        Validar_Gestionar_Usuarios.setText("0");

        Validar_Gestionar_Mesas.setText("0");

        Validar_Gestionar_Negocio.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Validar_Ventas_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar_Gestionar_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Validar_Ventas_Por_Mayor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Validar_Gestionar_Proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar_Gestionar_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar_Gestionar_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Validar_Gestionar_Categorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Validar_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Validar_Gestionar_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Validar_Gestionar_Negocio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Validar_Gestionar_Mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Validar_Gestionar_Proveedores)
                            .addComponent(Validar_Gestionar_Compras)
                            .addComponent(Validar_Gestionar_Productos)
                            .addComponent(Validar_Inventario)
                            .addComponent(Validar_Gestionar_Usuarios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Validar_Gestionar_Categorias)
                            .addComponent(Validar_Gestionar_Mesas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar_Gestionar_Negocio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Validar_Ventas_Bar)
                            .addComponent(Validar_Gestionar_Clientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Validar_Ventas_Por_Mayor)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 826, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        MenuBar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N

        Menu_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/punto-de-venta.png"))); // NOI18N
        Menu_Ventas.setText("Ventas");

        Menu_VentasBar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_VentasBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/barra-de-bar.png"))); // NOI18N
        Menu_VentasBar.setText("Ventas Bar");
        Menu_VentasBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_VentasBarActionPerformed(evt);
            }
        });
        Menu_Ventas.add(Menu_VentasBar);

        Menu_VentasPorMayor.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_VentasPorMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botella-de-vino.png"))); // NOI18N
        Menu_VentasPorMayor.setText("Ventas Por Mayor");
        Menu_VentasPorMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_VentasPorMayorActionPerformed(evt);
            }
        });
        Menu_Ventas.add(Menu_VentasPorMayor);

        MenuBar.add(Menu_Ventas);

        Menu_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apreton-de-manos.png"))); // NOI18N
        Menu_Clientes.setText("Clientes");

        Menu_Gestionar_Clientes.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Gestionar_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestion-de-la-relacion-con-el-cliente.png"))); // NOI18N
        Menu_Gestionar_Clientes.setText("Gestionar Clientes");
        Menu_Gestionar_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestionar_ClientesActionPerformed(evt);
            }
        });
        Menu_Clientes.add(Menu_Gestionar_Clientes);

        jMenuItem1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem1.setText("Historial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu_Clientes.add(jMenuItem1);

        MenuBar.add(Menu_Clientes);

        Menu_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proveedores.png"))); // NOI18N
        Menu_Proveedores.setText("Proveedores");

        Menu_Gestionar_Proveedores.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Gestionar_Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cadena-de-suministro.png"))); // NOI18N
        Menu_Gestionar_Proveedores.setText("Gestionar Proveedores");
        Menu_Gestionar_Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestionar_ProveedoresActionPerformed(evt);
            }
        });
        Menu_Proveedores.add(Menu_Gestionar_Proveedores);

        MenuBar.add(Menu_Proveedores);

        Menu_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/metodo-de-pago.png"))); // NOI18N
        Menu_Compras.setText("Compras");

        Menu_Gestionar_Compras.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Gestionar_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pedido.png"))); // NOI18N
        Menu_Gestionar_Compras.setText("Gestionar Compras");
        Menu_Gestionar_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestionar_ComprasActionPerformed(evt);
            }
        });
        Menu_Compras.add(Menu_Gestionar_Compras);

        MenuBar.add(Menu_Compras);

        Menu_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/espiritu2.png"))); // NOI18N
        Menu_Productos.setText("Productos");

        Menu_Gestionar_Productos.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Gestionar_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/espiritu2.png"))); // NOI18N
        Menu_Gestionar_Productos.setText("Gestionar Productos");
        Menu_Gestionar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestionar_ProductosActionPerformed(evt);
            }
        });
        Menu_Productos.add(Menu_Gestionar_Productos);

        MenuBar.add(Menu_Productos);

        Menu_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informe-de-venta.png"))); // NOI18N
        Menu_Reportes.setText("Reportes");

        Menu_Reporte_Inventario.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Reporte_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informe-de-venta.png"))); // NOI18N
        Menu_Reporte_Inventario.setText("Inventario");
        Menu_Reporte_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reporte_InventarioActionPerformed(evt);
            }
        });
        Menu_Reportes.add(Menu_Reporte_Inventario);

        Menu_Reporte_Ventas_Bar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Reporte_Ventas_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informe-de-venta.png"))); // NOI18N
        Menu_Reporte_Ventas_Bar.setText("Ventas Bar");
        Menu_Reportes.add(Menu_Reporte_Ventas_Bar);

        Menu_Reporte_Ventar_Por_Mayor.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Reporte_Ventar_Por_Mayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/informe-de-venta.png"))); // NOI18N
        Menu_Reporte_Ventar_Por_Mayor.setText("Ventas Por Mayor");
        Menu_Reportes.add(Menu_Reporte_Ventar_Por_Mayor);

        MenuBar.add(Menu_Reportes);

        Menu_Gestion.setText("Gestion");

        Menu_Registro_Usuarios.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Registro_Usuarios.setText("Usuarios");
        Menu_Registro_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Registro_UsuariosActionPerformed(evt);
            }
        });
        Menu_Gestion.add(Menu_Registro_Usuarios);

        Menu_Mesas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Mesas.setText("Mesas");
        Menu_Gestion.add(Menu_Mesas);

        Menu_Datos_Negocio.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Menu_Datos_Negocio.setText("Datos Negocio");
        Menu_Gestion.add(Menu_Datos_Negocio);

        MenuBar.add(Menu_Gestion);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir del sistema?", "WARNING", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void Menu_VentasBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_VentasBarActionPerformed
        if (Validar_Ventas_Bar.getText() == "0") {
            FrmVentas_Bar vb = new FrmVentas_Bar();
            vb.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana VENTAS BAR ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_VentasBarActionPerformed

    private void Boton_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CerrarSesionActionPerformed
        FrmLogin lg = new FrmLogin();

        int respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar sesion?", "WARNING", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose();
            lg.setVisible(true);
        }
    }//GEN-LAST:event_Boton_CerrarSesionActionPerformed

    private void Menu_VentasPorMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_VentasPorMayorActionPerformed
        if (Validar_Ventas_Por_Mayor.getText() == "0") {
            FrmVentas_Por_Mayor vpm = new FrmVentas_Por_Mayor();
            vpm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana VENTAS POR MAYOR ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_VentasPorMayorActionPerformed

    private void Menu_Gestionar_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestionar_ClientesActionPerformed
        if (Validar_Gestionar_Clientes.getText() == "0") {
            FrmClientes cl = new FrmClientes();
            cl.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana GESTIONAR CLIENTES ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Gestionar_ClientesActionPerformed

    private void Menu_Gestionar_ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestionar_ProveedoresActionPerformed
        if (Validar_Gestionar_Proveedores.getText() == "0") {
            FrmProveedores pv = new FrmProveedores();
            pv.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana GESTIONAR PROVEEDORES ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Gestionar_ProveedoresActionPerformed

    private void Menu_Gestionar_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestionar_ComprasActionPerformed
        if (Validar_Gestionar_Compras.getText() == "0") {
            FrmCompras cp = new FrmCompras();
            cp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana GESTIONAR COMPRAS ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Gestionar_ComprasActionPerformed

    private void Menu_Reporte_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reporte_InventarioActionPerformed
        if (Validar_Inventario.getText() == "0") {
            FrmInventario inv = new FrmInventario();
            inv.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana INVENTARIO ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Reporte_InventarioActionPerformed

    private void Menu_Gestionar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestionar_ProductosActionPerformed
        if (Validar_Gestionar_Productos.getText() == "0") {
            FrmProductos prod = new FrmProductos();
            prod.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana PRODUCTOS ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Gestionar_ProductosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmHistorialCliente hc = new FrmHistorialCliente();
        hc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Menu_Registro_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Registro_UsuariosActionPerformed
        if (Validar_Gestionar_Usuarios.getText() == "0") {
            FrmRegistroUsuarios regusu = new FrmRegistroUsuarios();
            regusu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana USUARIOS ya se encuentra abierta");
        }
    }//GEN-LAST:event_Menu_Registro_UsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_CerrarSesion;
    private javax.swing.JMenuBar MenuBar;
    public static javax.swing.JMenu Menu_Clientes;
    public static javax.swing.JMenu Menu_Compras;
    public static javax.swing.JMenuItem Menu_Datos_Negocio;
    public static javax.swing.JMenu Menu_Gestion;
    public static javax.swing.JMenuItem Menu_Gestionar_Clientes;
    public static javax.swing.JMenuItem Menu_Gestionar_Compras;
    public static javax.swing.JMenuItem Menu_Gestionar_Productos;
    public static javax.swing.JMenuItem Menu_Gestionar_Proveedores;
    public static javax.swing.JMenuItem Menu_Mesas;
    public static javax.swing.JMenu Menu_Productos;
    public static javax.swing.JMenu Menu_Proveedores;
    public static javax.swing.JMenuItem Menu_Registro_Usuarios;
    public static javax.swing.JMenuItem Menu_Reporte_Inventario;
    public static javax.swing.JMenuItem Menu_Reporte_Ventar_Por_Mayor;
    public static javax.swing.JMenuItem Menu_Reporte_Ventas_Bar;
    public static javax.swing.JMenu Menu_Reportes;
    public static javax.swing.JMenu Menu_Ventas;
    public static javax.swing.JMenuItem Menu_VentasBar;
    public static javax.swing.JMenuItem Menu_VentasPorMayor;
    public static javax.swing.JLabel Nombre_Usuario;
    public static javax.swing.JLabel Rol;
    public static javax.swing.JLabel Username;
    public static javax.swing.JLabel Validar_Gestionar_Categorias;
    public static javax.swing.JLabel Validar_Gestionar_Clientes;
    public static javax.swing.JLabel Validar_Gestionar_Compras;
    public static javax.swing.JLabel Validar_Gestionar_Mesas;
    public static javax.swing.JLabel Validar_Gestionar_Negocio;
    public static javax.swing.JLabel Validar_Gestionar_Productos;
    public static javax.swing.JLabel Validar_Gestionar_Proveedores;
    public static javax.swing.JLabel Validar_Gestionar_Usuarios;
    public static javax.swing.JLabel Validar_Inventario;
    public static javax.swing.JLabel Validar_Ventas_Bar;
    public static javax.swing.JLabel Validar_Ventas_Por_Mayor;
    public static javax.swing.JLabel idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
